### ISSUE TITLE
Game Compiling Error

### ISSUE THREAD

**Issue by GenericGaming** [Verwex/Funkin-Mic-d-Up-SC#10]
So, I downloaded the source code of the game so I could compile it for mac, I followed all the instructions and updated all of the required libraries. And I still get an error, I don't know if this is an OS issue, but if it is then, i'm stupid. If it is my own error i'm sorry for wasting whoever reads this thread's time.

Here's the error message, it's massive:
source/FirstCheckState.hx:9: characters 8-15 : Module Discord does not define type Discord
source/MenuModifiers.hx:4: characters 8-15 : Module Discord does not define type Discord
source/MenuModifiers.hx:183: characters 4-17 : Type not found : DiscordClient
source/PlaySelection.hx:4: characters 8-15 : Module Discord does not define type Discord
source/MenuModifiers.hx:303: characters 6-19 : Type not found : DiscordClient
source/Substate_Preset.hx:11: characters 8-15 : Module Discord does not define type Discord
source/Substate_PresetSave.hx:16: characters 8-15 : Module Discord does not define type Discord
source/Substate_PresetLoad.hx:11: characters 8-15 : Module Discord does not define type Discord
source/Marathon_Substate.hx:12: characters 8-15 : Module Discord does not define type Discord
source/PlayState.hx:5: characters 8-15 : Module Discord does not define type Discord
source/Endless_Substate.hx:13: characters 8-15 : Module Discord does not define type Discord
source/MenuEndless.hx:13: characters 8-15 : Module Discord does not define type Discord
source/Endless_Substate.hx:210: characters 6-19 : Type not found : DiscordClient
source/Substate_ChartType.hx:10: characters 8-15 : Module Discord does not define type Discord
source/Substate_ChartType.hx:147: characters 6-19 : Type not found : DiscordClient
source/MenuEndless.hx:246: characters 4-17 : Type not found : DiscordClient
source/MenuEndless.hx:198: characters 29-42 : Type not found : DiscordClient
/usr/local/lib/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
/usr/local/lib/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/PlayState.hx:358: characters 3-16 : Type not found : DiscordClient
source/PlayState.hx:361: characters 4-17 : Type not found : DiscordClient
source/MenuWeek.hx:20: characters 8-15 : Module Discord does not define type Discord
source/MenuMarathon.hx:13: characters 8-15 : Module Discord does not define type Discord
source/PlayState.hx:2767: characters 7-20 : Type not found : DiscordClient
source/MenuMarathon.hx:180: characters 4-17 : Type not found : DiscordClient
source/MenuFreeplay.hx:9: characters 8-15 : Module Discord does not define type Discord
source/MenuFreeplay.hx:514: characters 5-18 : Type not found : DiscordClient
source/MenuFreeplay.hx:516: characters 5-18 : Type not found : DiscordClient
source/MenuFreeplay.hx:518: characters 5-18 : Type not found : DiscordClient
source/MenuFreeplay.hx:520: characters 5-18 : Type not found : DiscordClient
source/MenuFreeplay.hx:522: characters 5-18 : Type not found : DiscordClient
source/MenuFreeplay.hx:524: characters 6-19 : Type not found : DiscordClient
source/MenuFreeplay.hx:308: characters 7-20 : Type not found : DiscordClient
source/MenuFreeplay.hx:319: characters 7-20 : Type not found : DiscordClient
source/MenuWeek.hx:417: characters 4-17 : Type not found : DiscordClient
source/MenuWeek.hx:450: characters 4-17 : Type not found : DiscordClient
source/MenuWeek.hx:362: characters 6-19 : Type not found : DiscordClient
source/MenuWeek.hx:294: characters 5-18 : Type not found : DiscordClient
source/PlayState.hx:1867: characters 5-18 : Type not found : DiscordClient
source/PlayState.hx:1871: characters 5-18 : Type not found : DiscordClient
source/PlayState.hx:1886: characters 6-19 : Type not found : DiscordClient
source/PlayState.hx:1890: characters 6-19 : Type not found : DiscordClient
source/PlayState.hx:1903: characters 5-18 : Type not found : DiscordClient
source/PlayState.hx:2047: characters 6-19 : Type not found : DiscordClient
source/PlayState.hx:2057: characters 6-19 : Type not found : DiscordClient
source/PlayState.hx:2389: characters 7-20 : Type not found : DiscordClient
source/PAGE1settings.hx:4: characters 8-15 : Module Discord does not define type Discord
source/PAGE1settings.hx:89: characters 4-17 : Type not found : DiscordClient
source/PAGE2settings.hx:4: characters 8-15 : Module Discord does not define type Discord
source/PAGE2settings.hx:90: characters 4-17 : Type not found : DiscordClient
source/PAGE3settings.hx:5: characters 8-15 : Module Discord does not define type Discord
source/PAGE3settings.hx:88: characters 4-17 : Type not found : DiscordClient
source/PAGE4settings.hx:4: characters 8-15 : Module Discord does not define type Discord
source/PAGE4settings.hx:91: characters 4-17 : Type not found : DiscordClient
source/PAGE5settings.hx:8: characters 8-15 : Module Discord does not define type Discord
source/PAGE5settings.hx:89: characters 4-17 : Type not found : DiscordClient
source/PAGE6settings.hx:8: characters 8-15 : Module Discord does not define type Discord
source/PAGE6settings.hx:89: characters 4-17 : Type not found : DiscordClient
source/PAGE6settings.hx:156: characters 24-37 : Type not found : DiscordClient
source/MainMenuState.hx:4: characters 8-15 : Module Discord does not define type Discord
source/MainMenuState.hx:282: characters 3-16 : Type not found : DiscordClient
source/MainMenuState.hx:187: characters 5-18 : Type not found : DiscordClient
source/TitleStateReturn.hx:4: characters 8-15 : Module Discord does not define type Discord
source/MainMenuState.hx:203: characters 7-20 : Type not found : DiscordClient
source/MainMenuState.hx:211: characters 6-19 : Type not found : DiscordClient
source/MainMenuState.hx:234: characters 12-25 : Type not found : DiscordClient
source/MainMenuState.hx:239: characters 12-25 : Type not found : DiscordClient
source/TitleStateReturn.hx:63: characters 4-17 : Type not found : DiscordClient
source/TitleStateReturn.hx:179: characters 4-17 : Type not found : DiscordClient
source/PAGE5settings.hx:153: characters 24-37 : Type not found : DiscordClient
source/PAGE5settings.hx:174: characters 40-53 : Type not found : DiscordClient
source/PAGE5settings.hx:180: characters 40-53 : Type not found : DiscordClient
source/PAGE5settings.hx:195: characters 24-37 : Type not found : DiscordClient
source/PAGE4settings.hx:177: characters 24-37 : Type not found : DiscordClient
source/PAGE3settings.hx:150: characters 24-37 : Type not found : DiscordClient
source/PAGE2settings.hx:174: characters 24-37 : Type not found : DiscordClient
source/PAGE1settings.hx:176: characters 24-37 : Type not found : DiscordClient
source/Marathon_Substate.hx:150: characters 7-20 : Type not found : DiscordClient
source/Marathon_Edit.hx:13: characters 8-15 : Module Discord does not define type Discord
source/Substate_PresetSaveOK.hx:14: characters 8-15 : Module Discord does not define type Discord
source/PlaySelection.hx:287: characters 4-17 : Type not found : DiscordClient
source/PlaySelection.hx:180: characters 5-18 : Type not found : DiscordClient
source/PlaySelection.hx:197: characters 5-18 : Type not found : DiscordClient
source/PlaySelection.hx:225: characters 11-24 : Type not found : DiscordClient
source/PlaySelection.hx:230: characters 11-24 : Type not found : DiscordClient
source/PlaySelection.hx:235: characters 11-24 : Type not found : DiscordClient
source/PlaySelection.hx:240: characters 11-24 : Type not found : DiscordClient
source/PlaySelection.hx:245: characters 11-24 : Type not found : DiscordClient
source/FirstCheckState.hx:27: characters 3-16 : Type not found : DiscordClient
source/FirstCheckState.hx:30: characters 4-17 : Type not found : DiscordClient
source/FirstTimeState.hx:11: characters 8-15 : Module Discord does not define type Discord
source/TitleState.hx:4: characters 8-15 : Module Discord does not define type Discord
source/TitleState.hx:117: characters 5-18 : Type not found : DiscordClient
source/TitleState.hx:226: characters 4-17 : Type not found : DiscordClient
source/TitleState.hx:296: characters 4-17 : Type not found : DiscordClient
source/FirstTimeState.hx:30: characters 5-18 : Type not found : DiscordClient

**Comment by Verwex** [comment]
Maybe it's because of all the '#if desktop' checks around discord events. Try changing them to '#if windows' and then we'll see if that solves it.

**Comment by otherlego** [comment]
If you are compiling on mac would you change it to '#if mac' ?

**Comment by otherlego** [comment]
I think it's an issue of them not finding the discord stuff. Would I be able to delete it altogether

**Comment by TentaRJ** [comment]
This isn't a mac problem, I just don't think you installed DiscordClient properly. Make sure you have the right version of Git-SCM...

**Comment by TentaRJ** [comment]
# This has been figured out now! Check out my pull request that fixes it: #12 

###### Can't wait for it not to get pushed for days lmao

**Comment by otherlego** [comment]
Okay, gonna compile real quick

**Comment by otherlego** [comment]
I get an error saying:
`source/TitleState.hx:296: characters 4-11 : Module Discord does not define type Discord`

Any ideas to fix?

**Comment by AlexGamingSW** [comment]
> I get an error saying:
> `source/TitleState.hx:296: characters 4-11 : Module Discord does not define type Discord`
> 
> Any ideas to fix?

Same here, you need to change #if desktop to #if windows

**Comment by otherlego** [comment]
But then it doesn't work..... I'm on mac.

**Comment by TentaRJ** [comment]
@GenericGaming Please close this request, now that it was fixed in #12
