### ISSUE TITLE
Question: help. i cant rebuild systools

### ISSUE THREAD

**Issue by boyangsic** [Verwex/Funkin-Mic-d-Up-SC#104]
if i try to rebuild, it prints error 
'windows.h': No such file or directory

**Comment by boyangsic** [comment]
i installed all needs but i getting same error

**Comment by ghost** [comment]
Did you use haya's repo?
if not, run `haxelib git systools https://github.com/haya3218/systools`
and then try rebuilding it `lime rebuild systools (your os)`

**Comment by boyangsic** [comment]
yes.

**Comment by boyangsic** [comment]
this is same happend when i try to build original fnf.

**Comment by ghost** [comment]
Hmm, can try downloading these from visual studio and see if the problem still persists?
```
* C++ CMake tools for windows 
* C++ Profiling tools 
* C++ ATL for v142 build tools (x86 & x64)
* C++ MFC for v142 build tools (x86 & x64)
* C++/CLI support for v142 build tools (14.21)
* C++ Modules for v142 build tools (x64/x86)
* Clang Compiler for Windows
* MSVC v140 - VS 2015 C++ build tools (v14.00) 
* MSVC v141 - VS 2017 C++ x64/x86 build tools
* MSVC v142 - VS 2019 C++ x64/x86 build tools
* Windows 10 SDK (10.0.16299.0)
* Windows 10 SDK (10.0.17134.0)
* Windows SDK (10.0.17763.0)
```

**Comment by boyangsic** [comment]
what version is  C++ ATL for v142 build tools (x86 & x64) and C++ MFC for v142 build tools (x86 & x64)?

**Comment by ghost** [comment]
In the individual workloads tab you could search for those, they should be there.

Microsoft.VisualStudio.Component.VC.ATLMFC 16.4.29313.120
Microsoft.VisualStudio.Component.VC.ATL  16.4.29313.120

But if you select Desktop development with C++ and then it should appear in the optional items list, too

**Comment by boyangsic** [comment]
yea. installed it. but nothing is changed.

**Comment by ghost** [comment]
Restart your PC? Other than that, i don't really know, sorry.
Windows SDK _should've_ fixed that

**Comment by boyangsic** [comment]
can you send me .vsconfig file?

**Comment by boyangsic** [comment]
okay. i used original fnf .vsconfig file, but it same happend

**Comment by boyangsic** [comment]
plss help

**Comment by haya3218** [comment]
> plss help

uh, what operating system do you use

**Comment by haya3218** [comment]
Currently it only works on windows.
You know what I'll do a small patch that allows for turning off and on systools

**Comment by haya3218** [comment]
Patch has been implemented. If there are any compile errors, let me know
