### ISSUE TITLE
Bug Report: cant compile 

### ISSUE THREAD

**Issue by prockscac** [Verwex/Funkin-Mic-d-Up-SC#107]
whenever I try and compile the game it says  Funkin-Mic-d-Up-SC-stable % lime test mac -debug 
/Users/name/haxelib install newgrounds/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
/Users/justinspain/haxelib install newgrounds/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/VideoState.hx:70: characters 31-46 : Cannot access static field SKIP_STEP_LIMIT from a class instance
I downloaded the GrowtopiaFli extension but it still doesn't work.

**Comment by YousefTamer67** [comment]
i fixed the issue

**Comment by YousefTamer67** [comment]
erase this line of this code of videostate.hx. it will work.

**Comment by prockscac** [comment]
> erase this line of this code of videostate.hx. it will work.

whats the code?

**Comment by Verwex** [comment]
Had the exact same issue before pushing this extension-webm change, but what helped on my end is to uninstall extension-webm and then do a clean install and rebuild.

Did you install any other extension-webms like one Kade Engine uses beforehand by any chance?

**Comment by prockscac** [comment]
> Had the exact same issue before pushing this extension-webm change, but what helped on my end is to uninstall extension-webm and then do a clean install and rebuild.
> 
> Did you install any other extension-webms like one Kade Engine uses beforehand by any chance?

I finally got rid of the extension problem, I compiled the game and it was compiling and it finished compiling but instead of opening the game it said, Called from VideoState::boot VideoState.hx line 30
Called from cpp.Lib::load /usr/local/lib/haxe/std/cpp/Lib.hx line 38
Error : Could not load module webmHelper@GetFramecount__1

**Comment by LaxModsStuff** [comment]
> Had the exact same issue before pushing this extension-webm change, but what helped on my end is to uninstall extension-webm and then do a clean install and rebuild.

How do I uninstall extension-webm? I think I installed Kade's before any other version, so I'm not sure if that's going to cause any problems. Also, for reference, I'm getting a similar error:
`source/VideoState.hx:70: characters 31-46 : Cannot access static field SKIP_STEP_LIMIT from a class instance`
I also use Windows (just in case you need that info to help me)

**Comment by TentaRJ** [comment]
> > Had the exact same issue before pushing this extension-webm change, but what helped on my end is to uninstall extension-webm and then do a clean install and rebuild.
> 
> 
> 
> How do I uninstall extension-webm? I think I installed Kade's before any other version, so I'm not sure if that's going to cause any problems. Also, for reference, I'm getting a similar error:
> 
> `source/VideoState.hx:70: characters 31-46 : Cannot access static field SKIP_STEP_LIMIT from a class instance`
> 
> I also use Windows (just in case you need that info to help me)

'haxelib uninstall extension-webm' and then install the one you need.

**Comment by haya3218** [comment]
^^^^^
