### ISSUE TITLE
Bug Report: Systools preventing compile

### ISSUE THREAD

**Issue by DOGZ1234** [Verwex/Funkin-Mic-d-Up-SC#108]
### What operating system are you using the engine on?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
macOS
## What version of the engine are you using? Is the version from a stable release or compiled from current source code? Specify below.
current source code
## Please describe your issue. Provide extensive detail and images if possible.
/usr/local/lib/haxe/lib/systools/1,1,0/systools/win/Tools.hx:52: characters 13-34 : Variable requires type-hint or initialization 
This is the only line that could prevent it from compiling

**Comment by haya3218** [comment]
Please use my repo as the original systools hasn't been updated in years.
