### ISSUE TITLE
Question: how i do to convert a lua modchart to hx modchart?

### ISSUE THREAD

**Issue by FlakyMC** [Verwex/Funkin-Mic-d-Up-SC#109]
how i do to convert a lua modchart to hx modchart? because me and my friend do not know how to do modcharts in hscript

**Comment by Haudattu** [comment]
Hello! I have the same question :)

**Comment by Verwex** [comment]
There is no Lua to Hscript conversion tools as of writing this so I believe the only way for now is to uhhhh.... Write it from scratch.

Unless you wanna use the experimental branch of this project which has lua modcharts, just buggy in general. And it pains me how broken it can be in general with some options like background alpha e.g. so I refuse to fix it for now.

**Comment by FlakyMC** [comment]
ok :/

**Comment by haya3218** [comment]
> converter

will probably never happen. im kinda shit at making converters for modchart formats
