### ISSUE TITLE
Bug Report: Always Wavy Held Notes

### ISSUE THREAD

**Issue by lavenNooby** [Verwex/Funkin-Mic-d-Up-SC#114]
Windows (`x86_64`)

For some reason all of the held notes in all of the songs like to wiggle around. I don't have any modifiers on and I tried using default config as well, but they still act like snakes. No modchart either.

![image](https://user-images.githubusercontent.com/88544062/128517456-d48d3f8c-f988-499e-a1bc-0a8008f24186.png)
_what da note doin?_

**Comment by Pvrb1e** [comment]
not a bug
its a feature

**Comment by haya3218** [comment]
^^^
