### ISSUE TITLE
webmHelper@GetFramecount__1 error

### ISSUE THREAD

**Issue by DOGZ1234** [Verwex/Funkin-Mic-d-Up-SC#118]
### What operating system are you using the engine on?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Macos
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
try to launch the compiled app then launch it in terminal
## Please describe your issue. Provide extensive detail and images if possible.
Could not load module webmHelper@GetFramecount__1

**Comment by Pvrb1e** [comment]
#107

**Comment by DOGZ1234** [comment]
This is a completely different issue

**Comment by Pvrb1e** [comment]
dont delete the ndll files

**Comment by DOGZ1234** [comment]
i didn't touch them these are the unmodified files

**Comment by DOGZ1234** [comment]
I think it is because of the dll files.

**Comment by Pvrb1e** [comment]
u need the webm extension from this engine

**Comment by DOGZ1234** [comment]
I have it this is after it compiles

**Comment by DOGZ1234** [comment]
I think it doesn't load because i am on mac.

**Comment by shabman** [comment]
im having the same issue and idk why

**Comment by DOGZ1234** [comment]
I am closing this because The devs don't want to help.
