### ISSUE TITLE
Question: Wiggle notes

### ISSUE THREAD

**Issue by Nissan101** [Verwex/Funkin-Mic-d-Up-SC#124]
I noticed that this update made the held notes do this little wiggle animation. I was wondering if there was a way I could turn that off or if I was stuck using it?

**Comment by Havasi-Scarlet-5** [comment]
on Playstate.hx find this code : camSus.setFilters([susWiggle]);
and remove it or change it into : //camSus.setFilters([susWiggle]); in case you want to turn on again

**Comment by Nissan101** [comment]
That worked, thank you!

**Comment by Nissan101** [comment]
That worked, Thank You!
