### ISSUE TITLE
Question: Freeplay Records

### ISSUE THREAD

**Issue by DestenyLink2121** [Verwex/Funkin-Mic-d-Up-SC#13]
Where do I go in the code to make freeplay records work for mods

**Comment by Verwex** [comment]
What do you exactly mean by freeplay records?

**Comment by DestenyLink2121** [comment]
Iran as in the freeplay menu behind the heads of the characters there are spinning records with the characters colors on them, how do I make them work with custom characters?

**Comment by DestenyLink2121** [comment]
nvm, found out if you name it after the character in the xml it works
