### ISSUE TITLE
Question: How to add dialog to every week

### ISSUE THREAD

**Issue by Ghostdoesstuff** [Verwex/Funkin-Mic-d-Up-SC#14]
I need dialog for my mod  (weeks 1-3 for the demo) but the DialogueBox.hx file isn't like the normal/kade file so if anyone knows help

**Comment by DestenyLink2121** [comment]
you just have to put a dialogue file in there and it works! there is a tutorial in the data folder near the bottom

**Comment by Verwex** [comment]
Yes roughly how Desteny described it.

There is a tutorial in the data folder and for dialogue to work, you just need to put your dialogue where charts are present, under a certain name like in Senpai/Roses/Thorns dialogue and it will detect.

**Comment by Ghostdoesstuff** [comment]
oh
