### ISSUE TITLE
Question: Mic'd Up Engine Erroring Out when running `lime test windows -debug`

### ISSUE THREAD

**Issue by Turqee** [Verwex/Funkin-Mic-d-Up-SC#140]
Yo.
Making a mod with some friends, and I keep getting this error when i type `lime test windows -debug` `source/VideoState.hx:71: characters 31-46 : Cannot access static field SKIP_STEP_LIMIT from a class instance`. I am using the Mic'd Up Engine, and can only find solutions to kade engine, which are not working. Thanks in advance!

**Comment by Pvrb1e** [comment]
install the mic'd up version of webm lib
