### ISSUE TITLE
Bug Report: Double inputs not counting as a hit

### ISSUE THREAD

**Issue by Spel0** [Verwex/Funkin-Mic-d-Up-SC#15]
Basically the same problem as Sarvente engine had before it got updated, double input is being eaten and not counting, resulting in a miss. Strangely enough it doesn't happen in [Agoti mod](https://gamebanana.com/mods/284934), which uses same engine.

Video demonstration: https://www.youtube.com/watch?v=5jNVqye8__E

Version of Windows being used: Windows 10 pro 64-bit
Game is run on M2 SSD

**Comment by haya3218** [comment]
Fixed in next update. Its because of vanilla input being dumb

**Comment by KadeDev** [comment]
fixed in #35
