### ISSUE TITLE
Question: How do i make the week 7 assets work in playstate.hx?

### ISSUE THREAD

**Issue by DestenyLink2121** [Verwex/Funkin-Mic-d-Up-SC#22]
I copied a few of the week 7 assets (the tankmen crowd) and was wondering how to make these parts work

**Comment by Verwex** [comment]
Please don't bother. I found out recently that some of them are illegal for a gamebanana post and they will be cleared out in the next update. Go wait until real week 7 comes out on github, then you can go and do it.
