### ISSUE TITLE
Bug Report: Corrupted Winrar

### ISSUE THREAD

**Issue by Vegito234** [Verwex/Funkin-Mic-d-Up-SC#24]
Hello the file of the source code is corrupted please fix it and remove the corrupted file

**Comment by Verwex** [comment]
Sir, the packed source code file is not uploaded by me directly. Github does that job for me.

**Comment by Verwex** [comment]
Ye it must be your antivirus doing something wrong where it shouldn't. Try turning it off.

**Comment by Verwex** [comment]
oops gotta know if turning your antivirus did anything.

**Comment by Vegito234** [comment]
it wasn't the antivirus
