### ISSUE TITLE
Black lines

### ISSUE THREAD

**Issue by Vegito234** [Verwex/Funkin-Mic-d-Up-SC#26]
Do you know how I can add black lines for example this
![Screenshot_1](https://user-images.githubusercontent.com/79956763/118701858-0b403980-b7c9-11eb-8a62-b523ab58f8e8.jpg)

**Comment by Verwex** [comment]
Adobe Animate that up, and code in the animation afterwards.

**Comment by Vegito234** [comment]
yea but what is the name of the code @Verwex

**Comment by DestenyLink2121** [comment]
> yea but what is the name of the code @Verwex

found out that in adobe animate just name the black line dance the same as your character with no extras, just the name it works, but you also have to go to menustate.hx and put the name of the character after the senpai one

**Comment by Verwex** [comment]
and what Desteny said solves the issue
