### ISSUE TITLE
Bug Report: No EXE or Icon

### ISSUE THREAD

**Issue by Coolboy0516** [Verwex/Funkin-Mic-d-Up-SC#27]
### If you are playing the game in a browser, what site are you playing it from?
None

### If you are playing the game in a browser, what browser are you using?
None

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.
2.0.2
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
No
## Please describe your issue. Provide extensive detail and images if possible.
I followed the directions, but there isn't a exe
![image](https://user-images.githubusercontent.com/84407770/118704470-291b9780-b7e5-11eb-90b1-2103a7ecb461.png)

**Comment by TentaRJ** [comment]
Try compiling again and share the error from the control panel/powershell/terminal

**Comment by Coolboy0516** [comment]
didn't work
![image_2021-05-18_151307](https://user-images.githubusercontent.com/84407770/118709877-8ca8c380-b7eb-11eb-9b78-dbfd382ae715.png)

**Comment by TentaRJ** [comment]
> didn't work
> ![image_2021-05-18_151307](https://user-images.githubusercontent.com/84407770/118709877-8ca8c380-b7eb-11eb-9b78-dbfd382ae715.png)

you didn't code it properly...

**Comment by Coolboy0516** [comment]
oh.

**Comment by Coolboy0516** [comment]
> > didn't work
> > ![image_2021-05-18_151307](https://user-images.githubusercontent.com/84407770/118709877-8ca8c380-b7eb-11eb-9b78-dbfd382ae715.png)
> 
> you didn't code it properly...
