### ISSUE TITLE
Question: License 

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [Verwex/Funkin-Mic-d-Up-SC#28]
## What is your question?
I promise you that a one liner license is a bad idea. Maybe revert the change and add it to the readme?

**Comment by TentaRJ** [comment]
Its the Vanilla Repo's license. might wanna keep it for now...

**Comment by TheDrawingCoder-Gamer** [comment]
really? damn

**Comment by TheDrawingCoder-Gamer** [comment]
that wasn't a very smart decision on his part
