### ISSUE TITLE
Bug Report: APIStuff.HX already exlisting

### ISSUE THREAD

**Issue by Coolboy0516** [Verwex/Funkin-Mic-d-Up-SC#29]
#### Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, 
clearing AppData, trying another browser) before submitting an issue.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows 10 64 bit

## What version of the game are you using? Look in the bottom left corner of the main menu.
2.0.2
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Install and uncompress
## Please describe your issue. Provide extensive detail and images if possible.
![image](https://user-images.githubusercontent.com/84407770/118733882-3481b980-b80b-11eb-9948-6d67e78ce186.png)

**Comment by TentaRJ** [comment]
yeah but theres no values in there so its fine

**Comment by Coolboy0516** [comment]
it does have values

**Comment by TentaRJ** [comment]
Update your files. This was already fixed in #19 and #20.

**Comment by Coolboy0516** [comment]
I did, it's still the same, i got the zip version

**Comment by TentaRJ** [comment]
Download the code, not the release ZIP file...

**Comment by Coolboy0516** [comment]
ok

**Comment by Coolboy0516** [comment]
thx
