### ISSUE TITLE
Readme update request

### ISSUE THREAD

**Issue by VMGuy23** [Verwex/Funkin-Mic-d-Up-SC#31]
Haxe 4.2.1 works so I recommend updating the readme

**Comment by TentaRJ** [comment]
With all of the libraries needed? Are you sure? I tried it on Vanilla when it was still a problem that I needed to fix and it didn't seem to work...

**Comment by Verwex** [comment]
If it ain't broke, don't fix it.

**Comment by VMGuy23** [comment]
4.2.1 indeed works fully. Can compile on Linux with only deprecation warnings.
