### ISSUE TITLE
Question: getting errors whilst in the first part of the compiling guide

### ISSUE THREAD

**Issue by Salted-Beef** [Verwex/Funkin-Mic-d-Up-SC#32]
Around the parts where i have to run stuff like haxelib git polymod https://github.com/larsiusprime/polymod.git , I get this error:

"Error: could not clone Git repository"

im very new to this and i have no clue what im doing

Edit: i got past this bit, but i got no idea where the /source folder is, so im kinda stuck for the next part of the guide
Edit 2: i got past that bit and im at the last few steps of the guide, but im stuck on the part where you need to type "lime build windows -debug"
It gives me an error that states that "lime" is not recognized as an internal/external command, or batch file. What do i do?

**Comment by TentaRJ** [comment]
You need to set up lime with 'haxelib run lime setup'
