### ISSUE TITLE
Question: How to scale portraits

### ISSUE THREAD

**Issue by Ghostdoesstuff** [Verwex/Funkin-Mic-d-Up-SC#33]
![Scaling Error](https://user-images.githubusercontent.com/83383274/118924810-3464e500-b903-11eb-9f08-cb1e5db772b0.PNG)

My Scaling for my portrait sprites for dialog is messed up how do I fix it

**Comment by Verwex** [comment]
guess a minimum width of 256 so that the image is not scaled up 6 times is too much

**Comment by Ghostdoesstuff** [comment]
> 
> 
> guess a minimum width of 256 so that the image is not scaled up 6 times is too much
how do I do that

**Comment by TentaRJ** [comment]
> > guess a minimum width of 256 so that the image is not scaled up 6 times is too much
> 
> how do I do that

Haha image size go brr

**Comment by Ghostdoesstuff** [comment]
I think I got it
