### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by festtt** [Verwex/Funkin-Mic-d-Up-SC#36]
I downloaded the source code zip and when I open it so I can extract everything it says it's corrupted.

**Comment by VMGuy23** [comment]
Try file explorer. If not try 7-zip.

**Comment by Verwex** [comment]
> Try file explorer. If not try 7-zip.

No it's not that. I've gotten a similar issue to this one #24, and it must be Github getting drunk.

**Comment by VMGuy23** [comment]
Git clone > Download Zip

**Comment by haya3218** [comment]
This is most likely a github issue. Using GitHub Desktop to git the repo seems to have no problem.
