### ISSUE TITLE
Bug Report: Cant Compile For HTML5

### ISSUE THREAD

**Issue by Tannermanner2008** [Verwex/Funkin-Mic-d-Up-SC#37]
I Test My Mods In HTML5 so i dont have to wait for it to compile for windows but when i try to compile for html5 with this it gives me an error
MainVariables.hx:9: characters 8-19 : You cannot access the sys package while targeting js (for sys.io.File)

**Comment by Verwex** [comment]
Check the readme file. There is something **clearly** specified about html5 compiling.
