### ISSUE TITLE
Question:How to remove new difficulty

### ISSUE THREAD

**Issue by Ghostdoesstuff** [Verwex/Funkin-Mic-d-Up-SC#38]
For my mod i don't want to have those difficultys in as noob is to easy and expert and insane are kinda spammy

**Comment by ColdVee** [comment]
alright so, here's what you gotta do:
in menuweek.hx (or mostly anything has difficulties registered like the freeplaymenu n all)
you mostly just gotta set these to how i have em
![image](https://user-images.githubusercontent.com/82906511/119388027-6f379600-bcd2-11eb-91cb-0976bbe68d70.png)
![image](https://user-images.githubusercontent.com/82906511/119388066-7c548500-bcd2-11eb-9f63-a0b654381a68.png)
![image](https://user-images.githubusercontent.com/82906511/119388105-85455680-bcd2-11eb-8775-a26f8bd9b346.png)
![image](https://user-images.githubusercontent.com/82906511/119388122-8bd3ce00-bcd2-11eb-82da-f93a9b2ba95e.png)
![image](https://user-images.githubusercontent.com/82906511/119388146-91311880-bcd2-11eb-8e5c-17c221e66976.png)

**Comment by Ghostdoesstuff** [comment]
> 
> 
> alright so, here's what you gotta do:
> in menuweek.hx (or mostly anything has difficulties registered like the freeplaymenu n all)
> you mostly just gotta set these to how i have em
> ![image](https://user-images.githubusercontent.com/82906511/119388027-6f379600-bcd2-11eb-91cb-0976bbe68d70.png)
> ![image](https://user-images.githubusercontent.com/82906511/119388066-7c548500-bcd2-11eb-9f63-a0b654381a68.png)
> ![image](https://user-images.githubusercontent.com/82906511/119388105-85455680-bcd2-11eb-8775-a26f8bd9b346.png)
> ![image](https://user-images.githubusercontent.com/82906511/119388122-8bd3ce00-bcd2-11eb-82da-f93a9b2ba95e.png)
> ![image](https://user-images.githubusercontent.com/82906511/119388146-91311880-bcd2-11eb-8e5c-17c221e66976.png)
I did it
