### ISSUE TITLE
add spaces in names

### ISSUE THREAD

**Issue by jefftheholymemee** [Verwex/Funkin-Mic-d-Up-SC#43]
add spaces in song names. recently kade engine got a new feature where there where spaces in song names and some songs were also renamed, i think this would be a cool feature to have in the mod.

**Comment by TentaRJ** [comment]
that would be a hassle to implement due to how many files we would need to change... but maybe in the future...

**Comment by Verwex** [comment]
thank god for power tools to mass rename files and ofc some additional stuff

**Comment by TentaRJ** [comment]
> thank god for power tools to mass rename files and ofc some additional stuff
> 
> You thought I'd have to do them manually one by one? Work smarter with 3rd party software to do something, not harder.

True!!!
