### ISSUE TITLE
Bug Report: I don't know if this is a bug or not, but just in case I'll put the bug label on this. I decided to port a song onto Mic'd Up and it crashes.

### ISSUE THREAD

**Issue by IndigoDarkw0lf** [Verwex/Funkin-Mic-d-Up-SC#45]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
HTML5 compiling doesn't work with Mic'd Up.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
As I said, can't compile to HTML5.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x86_64

## What version of the game are you using? Look in the bottom left corner of the main menu.
MU 2.0.2

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
No I have not, because it keeps on happening.

## Please describe your issue. Provide extensive detail and images if possible.
https://user-images.githubusercontent.com/78701030/120049312-91d5f180-bfe7-11eb-96b5-22d9cefc40a7.mp4

**Comment by TentaRJ** [comment]
From [README.md](https://github.com/Verwex/Funkin-Mic-d-Up-SC/blob/main/README.md):

HTML Building:
HTML Compiling currently does not work as Mic'd Up! currently requires desktop-only libraries to function properly.

Please close this issue

**Comment by IndigoDarkw0lf** [comment]
> From [README.md](https://github.com/Verwex/Funkin-Mic-d-Up-SC/blob/main/README.md):
> 
> HTML Building:
> HTML Compiling currently does not work as Mic'd Up! currently requires desktop-only libraries to function properly.
> 
> Please close this issue

I already knew that. HTML5 isn't my problem.

**Comment by haya3218** [comment]
fixed in latest update (again)
