### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by Purble11** [Verwex/Funkin-Mic-d-Up-SC#50]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
windows 64 bit

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
![image](https://user-images.githubusercontent.com/84761876/120301537-035eba00-c2de-11eb-8298-3488da75434f.png)
this is where the line number leads to 
![image](https://user-images.githubusercontent.com/84761876/120301601-15d8f380-c2de-11eb-9b1a-d43524d93186.png)

## Please describe your issue. Provide extensive detail and images if possible.
so I got this error here source/PlayState.hx:1547: characters 2-9 : Expected } and I looked I don't see a problem in the code

**Comment by haya3218** [comment]
This might have been fixed
