### ISSUE TITLE
Bug Report: Notes only register if it is exactly on the right position

### ISSUE THREAD

**Issue by family1242** [Verwex/Funkin-Mic-d-Up-SC#52]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x86_64

## What version of the game are you using? Look in the bottom left corner of the main menu.
2.0.2, Source code

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
No, but I would assume I would have to change the code.

## Please describe your issue. Provide extensive detail and images if possible.
Hi,

Whenever I press the note, it doesn't register unless it is exactly in the right position. Is there a way to fix this?

**Comment by haya3218** [comment]
Fixed in upcoming update.
