### ISSUE TITLE
Question: Settable Buttons & Downscroll

### ISSUE THREAD

**Issue by GamingInfinite** [Verwex/Funkin-Mic-d-Up-SC#54]
Is this available in the current release, because I cannot find it anywhere despite both features being in Agoti and Starlight, both of which are mods using this as an engine of sorts.  And if they're not available in the base version of Mic'd up, then please add them because, and this may be just my problem, but it takes so much more energy for me to read up scroll, let alone play it on wasd or 4286 or arrow keys for that matter.  I much prefer to play on dfjk or zx 23.

**Comment by Verwex** [comment]
Will be in the next update, with more keybinds as normal as well because uhhhhhhhhhhhhhhhhhhhhhh




5k

**Comment by GamingInfinite** [comment]
Wait does that apply for downscroll as well?

**Comment by BoyfriendFNF** [comment]
> Will be in the next update, with more keybinds as normal as well because uhhhhhhhhhhhhhhhhhhhhhh
> 
> 5k

5 keys?
