### ISSUE TITLE
Pls answer it :(((((((((((

### ISSUE THREAD

**Issue by Afinoob** [Verwex/Funkin-Mic-d-Up-SC#55]
The question is how to fix this?

Compiling group: haxe
cl.exe -Iinclude -IC:/Users/user/Downloads/funkin master/Funkin-0.2.7-mod-2.0.1/MSVC/discord_rpc/git/linc/ -nologo -DHX_WINDOWS -D_USING_V140_SDK71_ -GR -O2(optim-std) -Zi(debug) -FdC:\Users\user\Downloads\Funkin-Mic-d-Up-SC-2.0.2.NO7\export\release\windows\obj\obj/msvc-ncxp/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -Oy- -c -EHs -GS- -arch:SSE2 -IC:/Users/user/Downloads/funkin master/Funkin-0.2.7-mod-2.0.1/MSVC/hxcpp/4,2,1/include -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/openfl/display/_internal/Context3DElementType.cpp
Process creation failure : cl.exe

**Comment by VMGuy23** [comment]
Hi - Have you downloaded everything? Have you got the latest version of Haxe installed?

**Comment by TentaRJ** [comment]
> Hi - Have you downloaded everything? Have you got the latest version of Haxe installed?

Haxe 4.1.5

**Comment by VMGuy23** [comment]
Hi - Try installing the latest version of Haxe (I think it's 4.2.2) and make sure to follow the build guide [here](https://github.com/ninjamuffin99/Funkin/blob/master/README.md).

**Comment by TentaRJ** [comment]
> Hi - Try installing the latest version of Haxe (I think it's 4.2.2) and make sure to follow the build guide [here](https://github.com/ninjamuffin99/Funkin/blob/master/README.md).

Haxe 4.1.5

**Comment by VMGuy23** [comment]
Hi - Please install Haxe 4.2.2.

**Comment by TentaRJ** [comment]
> Hi - Please install Haxe 4.2.2.

Haxe 4.1.5

**Comment by hdboye** [comment]
Haxe 4.1.5

**Comment by VMGuy23** [comment]
Haxe 4.1.5

**Comment by MatadorProBr** [comment]
Haxe 4.1.5

**Comment by VMGuy23** [comment]
4.2.2 needs to be installed

**Comment by Afinoob** [comment]
4.1.5 or 4.2.2?

**Comment by Afinoob** [comment]
> Hi - Have you downloaded everything? Have you got the latest version of Haxe installed?

i download 4.1.5

**Comment by VMGuy23** [comment]
> 4.1.5 or 4.2.2?

4.2.2
