### ISSUE TITLE
Bug Report: "Guitar Sustain" game crash

### ISSUE THREAD

**Issue by Spel0** [Verwex/Funkin-Mic-d-Up-SC#69]
How to reproduce: basically if you turn it on, it works fine. The only problem is that if you unhold the note that u successfully hit without holding it to the end, then the game crashes.

Was tested on windows 10, 64 bit system.

Video of the bug: https://www.youtube.com/watch?v=XK9Kdyq-HQQ

**Comment by Spel0** [comment]
Debug info
![image](https://user-images.githubusercontent.com/75626813/124085791-138ec400-da59-11eb-828a-fc7786c9f4d2.png)

**Comment by haya3218** [comment]
Will be fixed in next version.

**Comment by Verwex** [comment]
more like, possibly now on the public rep???
