### ISSUE TITLE
Bug Report: Wave hold notes persist in different modes

### ISSUE THREAD

**Issue by st4bbybunny** [Verwex/Funkin-Mic-d-Up-SC#77]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
-
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
-
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (x86)
## What version of the game are you using? Look in the bottom left corner of the main menu.
2.0.3
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
-
## Please describe your issue. Provide extensive detail and images if possible.
wavy hold notes in wave mode persist in other modes

**Comment by haya3218** [comment]
This is intentional

**Comment by Slyshii** [comment]
yo wtf can u please add an option to disable this, its so disorienting
