### ISSUE TITLE
Bug Report: Can't compile on Linux

### ISSUE THREAD

**Issue by VMGuy23** [Verwex/Funkin-Mic-d-Up-SC#79]
### If you are playing the game in a browser, what site are you playing it from?
---

### If you are playing the game in a browser, what browser are you using?
---

### If you are playing a downloaded version of the game, what operating system are you using?
Linux

## What version of the game are you using? Look in the bottom left corner of the main menu.
latest Git version
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Download source code on Linux
## Please describe your issue. Provide extensive detail and images if possible.
I try compile, I get this:
```
/home/stuff/.local/share/haxe/lib/systools/1,1,0/systools/win/Tools.hx:52: characters 13-34 : Variable requires type-hint or initialization
source/TitleState.hx:33: lines 33-504 : ... Defined in this class
```
as well as the usual XML deprecation errors. it just goes back to a prompt after that

**Comment by Purble11** [comment]
this is not bc ur on linux cuz I have it and i dont know how to fix it also
![image](https://user-images.githubusercontent.com/84761876/124475967-621ec400-ddb3-11eb-9a1b-38802c7007d2.png)

**Comment by Purble11** [comment]
the issue is that titlestate class is unknown
![image](https://user-images.githubusercontent.com/84761876/124489210-cba5cf00-ddc1-11eb-8e14-8cd1a2502e38.png)

**Comment by VMGuy23** [comment]
do you know how to fix?

**Comment by Purble11** [comment]
no

**Comment by Purble11** [comment]
I found a fix add "static var GET_RULES = null;" to line 52 for the file /home/stuff/.local/share/haxe/lib/systools/1,1,0/systools/win/Tools.hx

**Comment by Purble11** [comment]
i researched and its the problem with the ndll file not being the right one

**Comment by Purble11** [comment]
for win users do `haxelib git systools https://github.com/haya3218/systools` to fix it

**Comment by Purble11** [comment]
before u do it remove the broken one

**Comment by Purble11** [comment]
found the fix

**Comment by VMGuy23** [comment]
how

**Comment by Purble11** [comment]
#81 
there

**Comment by VMGuy23** [comment]
i figured it out

its really buggy though
