### ISSUE TITLE
Bug Report: API keys aren't gitignored

### ISSUE THREAD

**Issue by daniel11420** [Verwex/Funkin-Mic-d-Up-SC#8]
https://github.com/Verwex/Funkin-Mic-d-Up-SC/blob/main/source/APIStuff.hx

**Comment by TheDrawingCoder-Gamer** [comment]
This isn't a bug... no actual info is included in them. Original FNF gitignored them because they had info, but this one does not.

**Comment by TheDrawingCoder-Gamer** [comment]
oohhhhhhhhhhh i see. it does contain info :flushed:

**Comment by Verwex** [comment]
it was covered up
