### ISSUE TITLE
Bug Report: systools.ndll does not exist

### ISSUE THREAD

**Issue by Conquestor50** [Verwex/Funkin-Mic-d-Up-SC#81]
so when i was installing new haxelibs like systools, random and seedyrng.
while compiling when all of those were installed it said this
HaxeToolkit/haxe/lib/systools/1,1,0/ndll/Windows64/systools.ndll" does not exist
can anybody tell me how to fix this?

**Comment by VMGuy23** [comment]
i got the same

**Comment by VMGuy23** [comment]
i dont get the error anymore, didnt do that

**Comment by Purble11** [comment]
how did u fix it then

**Comment by VMGuy23** [comment]
idk
it just doesnt do that anymore

**Comment by Purble11** [comment]
so it fixed itself?

**Comment by Purble11** [comment]
how please help

**Comment by Purble11** [comment]
i found a fix is that remove the broken systools and do these I WAS DUMB AND DIDNT READ IT PROPERLY

![image](https://user-images.githubusercontent.com/84761876/124599513-cd7d9a00-de76-11eb-903e-58e32a12baed.png)

**Comment by VMGuy23** [comment]
it worked
