### ISSUE TITLE
Assets not loading into export folder

### ISSUE THREAD

**Issue by jefftheholymemee** [Verwex/Funkin-Mic-d-Up-SC#84]
hey i have a pretty big problem. when i add a asset (a recolored character or icons) in the assets folder (shared folder which is in assets) and then i compile the game, i test to see if my asset is in the game but it isnt its just the same old one. i checked the export folder and nothing was changed (basically the old assets are still there). this also happens with other engines. how can i fix this?

**Comment by Purble11** [comment]
if its a character put it in /shared/characters if its a bg then put it in one of the week folders and so on

**Comment by jefftheholymemee** [comment]
> if its a character put it in /shared/characters if its a bg then put it in one of the week folders and so on

the problem is i do that and when i recompile and test it, the old assets are still there

**Comment by VMGuy23** [comment]
add -clean to the compile command

**Comment by jefftheholymemee** [comment]
> add -clean to the compile command

thank you so much, it worked and everything was fine!

**Comment by Purble11** [comment]
or just delete the export folder they do the same
