### ISSUE TITLE
Please someone help i dont know if i did something wrong

### ISSUE THREAD

**Issue by Purble11** [Verwex/Funkin-Mic-d-Up-SC#86]
## What is your question?
the portrait and box don't show up and it cant be skipped
here is the dialogue file
[dialogue.txt](https://github.com/Verwex/Funkin-Mic-d-Up-SC/files/6779015/dialogue.txt)

**Comment by VMGuy23** [comment]
it needs to be :dad: no matter what

**Comment by Purble11** [comment]
bruh mic'd up uses somthing diff u dumb

**Comment by Purble11** [comment]
look in senpais week data files and u will see the dialogue uses a diff format idot

**Comment by Purble11** [comment]
it's not just
:dad: d
:bf: d
it's more customizable

**Comment by Ghostdoesstuff** [comment]
probs a scale problem

**Comment by Ghostdoesstuff** [comment]
if you wanna mess with scale look in dialogbox.hx

**Comment by Purble11** [comment]
ok
