### ISSUE TITLE
Compiling mod issue.

### ISSUE THREAD

**Issue by Timone06** [Verwex/Funkin-Mic-d-Up-SC#87]
Well, I followed all the steps for the mod compiling, but I'm stuck at the end of the tutorial.

When I put the "`lime build windows -debug`" command, the Terminal says : `export/debug/windows/haxe/ApplicationMain.hx:299: characters 48-52 : Type not found : Main.`

I've found the "ApplicationMain.hx" and I've read the line 299 at VSCode, for now, it is : `@:keep @:dox(hide) class DocumentClass extends Main {}`

However, I tried also to ignore this "issue" and inserted the `lime run windows -debug` command, the Terminal says : 

`'"Funkin MU.exe"' is not recognized as an interior or exterior command, an executable program exécutable or a command folder.`

Well I don't know what to do, do you guys have any solutions for that? I'll accept them volunteer! ^^

The screenshot :
![Bug Lime Build Windows](https://user-images.githubusercontent.com/46558224/124811499-d2b81300-df62-11eb-93a7-3691a4d7044d.png)

**Comment by VMGuy23** [comment]
```
lime rebuild systools windows
```

**Comment by Purble11** [comment]
if rebuilding systools doesn't work remove systools and install this `haxelib git systools https://github.com/haya3218/systools` and then do `lime rebuild systools (ur os)`
