### ISSUE TITLE
Enhancement: downscroll

### ISSUE THREAD

**Issue by ItsMeSleepy** [Verwex/Funkin-Mic-d-Up-SC#9]
do I have to say more?

I'm sorry but for me, rhythm games are just unplayable without downscroll. And I want to play the insane chaos versions of songs and I can't because one of the most basic settings aren't in one of the most well created settings menu for an fnf mod.

side note custom keybinds would be nice too so I won't have to fuck with auto hotkey

**Comment by Verwex** [comment]
downscroll done.

You can enjoy it once I update, because I work with the big updates manner.
