### ISSUE TITLE
Question: Weird notes

### ISSUE THREAD

**Issue by TheMadLad729** [Verwex/Funkin-Mic-d-Up-SC#94]
## How do I use these note types?
So I've been looking through the files and found yellow square notes in the note assets, and another note type called "mine notes". How do I use these new types in the chart editor? There's also a square note "base"
![arrowMINE](https://user-images.githubusercontent.com/85416320/125391466-91fd3700-e372-11eb-8b53-f39517162f85.png)
![arrowMINE-alt](https://user-images.githubusercontent.com/85416320/125391477-9590be00-e372-11eb-9c1a-020b09505ed1.png)
![Square Note](https://user-images.githubusercontent.com/85416320/125391856-26679980-e373-11eb-8406-cf661eb5d257.png)
Also, these things. There's some for every note type, including the square ones. I have a lot of questions, sorry...
![wtf are these](https://user-images.githubusercontent.com/85416320/125392235-ccb39f00-e373-11eb-86b1-2c34d0bd0d54.png)
Pixel versions
![arrowMINE-alt-pixel](https://user-images.githubusercontent.com/85416320/125393023-31bbc480-e375-11eb-8b5a-02bd80d5ccb0.png)
![arrowMINE-pixel](https://user-images.githubusercontent.com/85416320/125393024-31bbc480-e375-11eb-88b9-3616e9512646.png)
![Square Pixel](https://user-images.githubusercontent.com/85416320/125393152-66c81700-e375-11eb-9c05-b2eb3654eaea.png)

**Comment by Pvrb1e** [comment]
they are defined in the game code but u will have to do some coding if u need help I would suggest looking in the shaggy mod source

**Comment by Verwex** [comment]
okay so the square is the center note when you play in 5k, which can be toggled on in options menu under the gameplay page

mine notes are placed in chart by pressing M, these two textures are randomized (check the fucking issue megathread's FAQ) 

these arrows are rolls (If you played Not In The Groove 2, you'd know), which aren't implemented yet in code (that means you can't place them yet and use them) but are planned for later




That is if you're using the stable release.
If you're using the newest source code:
- center note is the same
- M and N place mine notes and death notes respectfully
- rolls have a special checkmark in the note tab

**Comment by haya3218** [comment]
Read the above. ^^^

**Comment by TheMadLad729** [comment]
oooohhhh i get it now, thanks
