### ISSUE TITLE
Question: Can u add lua modchart by myself?

### ISSUE THREAD

**Issue by Pvrb1e** [Verwex/Funkin-Mic-d-Up-SC#95]
## What is your question?
is it possible to add lua modchart to this engine by myself?

**Comment by ghost** [comment]
"Engine currently has no lua modchart support"

_https://github.com/Verwex/Funkin-Mic-d-Up-SC/issues/88#issuecomment-878232999_

**Comment by Pvrb1e** [comment]
ok i didnt see that they replied

**Comment by Pvrb1e** [comment]
cuz i closed it before
